### ISSUE TITLE
Minitest-chef-handler gem not installing properly on windows

### ISSUE THREAD

**Issue by trekr5** [calavera/minitest-chef-handler#86]
Hello,

I'm trying to install the minitest-chef-handler gem on a windows 8.1 machine (running Ruby 2.0.0) and have the following errors:-

C:\git\GG.Infra.UserManager>gem install minitest-chef-handler
Fetching: minitest-4.7.5.gem (100%)
Successfully installed minitest-4.7.5
Fetching: ci_reporter-1.9.3.gem (100%)
Successfully installed ci_reporter-1.9.3
Fetching: minitest-chef-handler-1.0.3.gem (100%)
Successfully installed minitest-chef-handler-1.0.3
Building native extensions.  This could take a while...
ERROR:  Error installing minitest-chef-handler:
        ERROR: Failed to build gem native extension.

    C:/opscode/chefdk/embedded/bin/ruby.exe extconf.rb
creating Makefile
/c/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/libyajl2-1.2.0/ext/libyajl2
extconf.rb:104:in `makemakefiles': unhandled exception
        from extconf.rb:138:in `<main>'

Gem files will remain installed in c:/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/libyajl2-1.2.0 for inspection.
Results logged to c:/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/libyajl2-1.2.0/ext/libyajl2/gem_make.out

I'm running the following Chef gems:-
chef (11.14.0.rc.2 x86-mingw32, 11.12.8 x86-mingw32)
chefspec (4.0.1)

Also when I attempt to do a require 'minitest-chef-handler' within irb, (require minitest-chef-handler gem) I receive the following error:-

C:\git\GG.Infra.UserManager>irb
irb(main):001:0> require 'minitest-chef-handler'
LoadError: cannot load such file -- chef
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from c:/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/minitest-chef-handler-1.0.3/lib/minitest-chef-handler/resources.rb:1:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from c:/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/minitest-chef-handler-1.0.3/lib/minitest-chef-handler.rb:3:in `<top (required)>'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):1
        from C:/opscode/chefdk/embedded/bin/irb:12:in `<main>'

Can someone please tell me how I can solve this problem?

**Comment by lamont-granquist** [comment]
this looks like a cygwin path:

/c/Users/aebirim/.chefdk/gem/ruby/2.0.0/gems/libyajl2-1.2.0/ext/libyajl2

the whole chef ecosystem doesn't support cygwin very well and we don't support it.  if you can't figure it out  on your own, its best to not use it.  chefdk itself is mingw based and not cygwin and you're probably crossing the streams.

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
